version: "3"

services:

    redis:
      image: redis:latest
      container_name: ipgeolocation-caching-service
      networks:
        - ipgeolocation-network
      ports:
        - "6379:6379"

    api-service-1:
      image: fujikomalan/ipgeolocation-api-service:v1
      container_name: api-service-1
      networks:
        - ipgeolocation-network
      env_file: .env
      environment:
        REDIS_HOST: ipgeolocation-caching-service
        REDIS_PORT: 6379
        APP_PORT: "8080"
        API_KEY: $api_key

    api-service-2:
      image: fujikomalan/ipgeolocation-api-service:v1
      container_name: api-service-2
      networks:
        - ipgeolocation-network
      env_file: .env
      environment:
        REDIS_HOST: ipgeolocation-caching-service
        REDIS_PORT: 6379
        APP_PORT: "8080"
        API_KEY: $api_key


    api-service-3:
      image: fujikomalan/ipgeolocation-api-service:v1
      container_name: api-service-3
      networks:
        - ipgeolocation-network
      env_file: .env
      environment:
        REDIS_HOST: ipgeolocation-caching-service
        REDIS_PORT: 6379
        APP_PORT: "8080"
        API_KEY: $api_key

    frontend1:
      image: fujikomalan/ipgeolocation-frontend:v1
      container_name: ipgeolocation-frontend-service-1
      networks:
        - ipgeolocation-network
      environment:
        API_SERVER: nginx
        API_SERVER_PORT: 8080
        API_PATH: /api/v1/


    frontend2:
      image: fujikomalan/ipgeolocation-frontend:v1
      container_name: ipgeolocation-frontend-service-2
      networks:
        - ipgeolocation-network
      environment:
        API_SERVER: nginx
        API_SERVER_PORT: 8080
        API_PATH: /api/v1/

    frontend3:
      image: fujikomalan/ipgeolocation-frontend:v1
      container_name: ipgeolocation-frontend-service-3
      networks:
        - ipgeolocation-network
      environment:
        API_SERVER: nginx
        API_SERVER_PORT: 8080
        API_PATH: /api/v1/

    nginx:
      image: nginx:1.15.12-alpine
      container_name: nginx
      restart: always  
      networks:
        - ipgeolocation-network
      volumes:
        - ./nginx-conf/:/etc/nginx/conf.d
        - ./cert/:/etc/ssl/certs

      ports:
        - "80:80"
        - "443:443"
        - "8080:8080"

networks:
  ipgeolocation-network:
